### ISSUE TITLE
Cambio url a tile di sfondo

### ISSUE THREAD

**Issue by LorenzoStucchi** [osmItalia/estratti_OSM_Italia#10]
- [x] WMI deve fornire l'url delle tile distribuite da WikiMedia Foundation e inserire l'url del progetto tra quelli autorizzati

**Comment by LorenzoStucchi** [comment]
Il link è https://maps.wikimedia.org/osm-intl/{z}/{x}/{y}.png ed è inserito nella pull request https://github.com/GISdevio/estratti_OSM_Italia/pull/11

**Comment by GabrielePrestifilippo** [comment]
Bisogna notificare che come url per l'utilizzo delle tiles ci sarebbero l'url di produzione e quello su github pages. 
Se necessario su github page possiamo cambiare tiles o dismettere il servizio.

**Comment by frafra** [comment]
@LorenzoStucchi Ho impostato un servizio di CI. L'indirizzo è corretto, ma c'è un problema di permessi nell'accedere all'immagine da certi indirizzi:

> Error: 403, Forbidden: Map tiles are restricted to Wikimedia & affiliated sites only. Please post on https://phabricator.wikimedia.org/T261694 if you believe your usage supports the Movement. at Sun, 02 May 2021 12:40:03 GMT

Puoi vedere il branch master qui: https://estratti-osm-italia.netlify.app/. Il mio suggerimento è di proporre una regola per permettere di sfruttare il sistema di CI per le anteprime. Anche senza tile layer, credo il sistema di CI sia utile per avere comunque una idea del risultato finale e cogliere in anticipo tutta una serie di problemi (dipendenze, sintassi, ecc.).

Quando proporrai una PR vedrai Netlify produrre una anteprima del sito, così puoi valutare se il risultato è corretto. Puoi anche tenere la PR come "Draft": basta che quando la crei sul bottone verde premi la freccia per aprire il menù per creare la PR come bozza. Dopodiché puoi fare tutti i commit che vuoi e quando sei soddisfatto togli lo stato di bozza e provvedo a fare il merge e il deploy finale sul server WMI.

Potresti anche essere interessato a cambiare l'attribuzione:
https://github.com/GISdevio/estratti_OSM_Italia/blob/85b35535441ae78c12ce096f2d226315b6e322a4/webapp/src/configuration.json#L9

**Comment by LorenzoStucchi** [comment]
@frafra Ciao, il server finale https://osmit-estratti.wmcloud.org/ è già abilitato all'uso delle tile di Wimikedia come indicato [qui](https://phabricator.wikimedia.org/T261694#6522276).
Se ritieni che sia meglio testare prima il risultato chiedo il suppurto di @valerio-bozzolan per la richiesta di inserire l'altro indirizzo tra quelli accettati.

L'attribuzione corretta è:

```
 "mapAttribution": "Wikimedia Maps. Map data &copy; <a href='http://osm.org/copyright'>OpenStreetMap</a> contributors. Realizzato da <a href='https: //gisdev.io'>GISdevio&nbsp; <img style='margin-bottom:-2px' height='12' src='https://gisdev.io/img/logo_short.png'></a>" 
```

**Comment by frafra** [comment]
@LorenzoStucchi corretta, grazie.

Penso sarebbe una buona cosa, ma il problema è che bisognerebbe dare l'accesso a tutti i sotto domini di netlify.app per le varie PR che vengono generate, tipo:
https://deploy-preview-12--estratti-osm-italia.netlify.app/

Non credo che Wikimedia accetterebbe una regola così ampia. Dato che il trasferimento del dominio ovviamente non è fattibile, non credo si possa fare molto. Bisognerà accontentarsi di anteprime senza layer di base :)

**Comment by valerio-bozzolan** [comment]
Penso anche io che difficilmente si permetterebbe qualsiasi sottodominio "a caso" di netifly.

Per avere il CI senza errori si può anche introdurre un flag di debug che attivi un tileserver alternativo. Può essere più comodo?

Ciau
