### ISSUE TITLE
Errore Estratti in Friuli Venezia Giulia

### ISSUE THREAD

**Issue by LorenzoStucchi** [osmItalia/estratti_OSM_Italia#13]
Non viene visualizzata correttamente la suddivisione per le province in Friuli Venezia Giulia, vedi immagine.

![regionefriuli](https://user-images.githubusercontent.com/29042221/122371988-97788480-cf60-11eb-9090-decdbfeecc60.png)

Vengono visualizzati solo i dati dei comuni della provincia di Udine.

![comuniudine](https://user-images.githubusercontent.com/29042221/122372420-f211e080-cf60-11eb-9bff-4910064d589f.png)

**Comment by frafra** [comment]
Al fine di avere una struttura dati uniforme (ovvero su 3 livelli) si è deciso di creare una grande finta provincia per le regioni che non hanno province, ovvero Valle D'Aosta e Friuli Venezia Giulia. Tale provincia riporta il nome della regione e include tutti i comuni sottostanti.

Lo script crea un codice ISTAT fittizio per tale provincia, basandosi sull'assunto che i codici ISTAT dei comuni appartenenti alla stessa regione inizino con gli stessi tre numeri. Questo è valido per la Valle d'Aosta, ma non per il Friuli Venezia Giulia.

**Comment by LorenzoStucchi** [comment]
@frafra credo ci sia un errore sul Friuli Venezia Giulia, in quanto in realtà ha 4 province:
- Gorizia https://www.openstreetmap.org/relation/179294
- Trieste https://www.openstreetmap.org/relation/179292
- Pordenone https://www.openstreetmap.org/relation/179293
- Udine https://www.openstreetmap.org/relation/179295

Ad ora viene estratta sola la provincia di Udine

**Comment by musuruan** [comment]
In realtà non vengono chiamate province, ma la loro funzione sembra quella: https://it.wikipedia.org/wiki/Ente_di_decentramento_regionale

**Comment by frafra** [comment]
Quante cose che si imparano :)

I comuni della Valle d'Aosta sono tutti collegati alla regione nel database di WM che lo script utilizza, mentre quelli del Friuli Venezia Giulia sono collegati alle relazioni che @LorenzoStucchi ha elencato, che mancano nel database.

Ho modificato lo script in modo tale da uniformare il caso del Friuli Venezia Giulia a quello della Valle d'Aosta, quindi ignorando gli enti di decentramento regionale. Nel caso si volesse far apparire anche questo livello di suddivisione, bisognerebbe modificare gli script che si occupano dell'estrazione dei dati in modo da aggiungere tali enti con le rispettive geometrie e rimuovere il codice specifico che gestisce il caso del Friuli Venezia Giulia dallo script.

@geofrizz hai idea del perché il livello 6 del FVG non sia presente nel database? Il codice che hai scritto tu mi pare corretto. L'unica cosa è che è stato rimesso il livello 6 alle relazioni che ha elencato Lorenzo soltanto un mese fa circa, quindi forse il database è stato generato per l'ultima volta prima di questa data; puoi confermare?

**Comment by frafra** [comment]
La correzione è stata applicata sul server nei termini sopra descritti. Suggerirei di chiudere questa issue e di aprirne una nuova qualora si desideri aggiungere delle suddivisioni di livello 6 al FVG come da recenti modifiche fatte su OSM.

**Comment by geofrizz** [comment]
Ciao frafra,
e' probabile che anche in Friuli siano state eliminate le province,
bisognerebbe verificare nel db ed eventualmente utilizzare uno degli script
per l'estrazione dei dati e la creazione degli script per la generazione
dei "tagli" sui pdf.

Dovrei verificare.
Ciao, Paolo

**Comment by frafra** [comment]
Grazie geofrizz. Confermo che manca nel database, quindi andrebbe generato nuovamente. Continueremo la discussione nella nuova issue.
