### ISSUE TITLE
osmand-regioni.sh mancante

### ISSUE THREAD

**Issue by frafra** [osmItalia/estratti_OSM_Italia#24]
https://github.com/osmItalia/estratti_OSM_Italia/blob/610f5ef577cbda728855975f78c33fed501e0009/backend/download_latest.sh#L25

Sul server ho trovato questo codice:

```bash
#!/bin/bash
#


java -Djava.util.logging.config.file=logging.properties -Xms64M -Xmx12G -cp "./OsmAndMapCreator.jar:lib/OsmAnd-core.jar:./lib/*.jar" "net.osmand.util.IndexBatchCreator" batch-files/regioni-batch.xml
```

Non è però menzionato nel file `READ.ME`, così come non si parla di Java o di `OsmAndMapCreator.jar` come dipendenza, quindi non sono sicuro sia una dimenticanza. @geofrizz puoi confermare se hai modo?

**Comment by frafra** [comment]
Ho provveduto ad aggiungere manualmente i file mancanti dal vecchio server integrandoli nella procedura.

**Comment by geofrizz** [comment]
Ciao Frafra,
Per la parte OsmAnd lo script e' stato generato partendo dalla
procedura messa a disposizione direttamente da Osmand.Non vi e' nulla
di personalizzato se non i parametri da passare al software ... venne
fatto un tot di anni fa e non e' mai stato aggiornato (ammesso che
esista una versione piu' recente!)
Ciao, Paolo

**Comment by frafra** [comment]
Ciao Paolo,
grazie, ho notato poi che c'erano file simili negli esempi, anche se differivano percorsi e i parametri per la memoria, quindi ho preferito usare il tuo, e generare il file di configurazione usando le variabili di ambiente :)
Purtroppo non va con l'ultima versione di Java, quindi sono dovuto stare un poco più indietro, ma vedo che c'è già una issue aperta in merito. Ho giocato un po' con le varie opzioni senza successo. Vedremo se sistemeranno :)
