### ISSUE TITLE
Centratura menu laterale su selezione

### ISSUE THREAD

**Issue by alesarrett** [osmItalia/estratti_OSM_Italia#8]
Quando si seleziona una regione tra quelle più in basso nel menù a destra, compare il pannello per il download dei dati che, a seconda della grandezza della finestra del browser, a volte oscura la regione e le province selezionate. L'utente deve semplicemente scrollare giù per vedere la selezione, ma sarebbe più funzionale fare in modo che il focus del menù a destra si allineasse immediatamente sulla regione e le province selezionate.
Es. di selezione del Veneto
![image](https://user-images.githubusercontent.com/1692316/112099669-367d2280-8ba4-11eb-85c2-375fd4726a37.png)

**Comment by GabrielePrestifilippo** [comment]
Grazie per la segnalazione! Abbiamo agiunto un fix in !686aaf5 che effettua uno scroll in automatico verso l'elemento selezionato. Così dovrebbe funzionare bene, il fix è già deployato nel server di sviluppo. Se dovesse ripresentarsi riapri pure la issue.
