### ISSUE TITLE
Aggiunta di un timestamp al file in download

### ISSUE THREAD

**Issue by alesarrett** [osmItalia/estratti_OSM_Italia#9]
I file che si scaricano non hanno informazioni su data e ora di riferimento del dato: sarebbe credo utile che nel nome del file (oppure in un README scaricato insieme ai dati?) venisse aggiunto un timestamp con data (e ora?) in formato ISO 8601 o semplificato.

**Comment by frafra** [comment]
Le date ISO 8601 con risoluzione temporale superiore all'ora utilizzano spesso il separatore `:` tra ore, minuti ed eventualmente secondi. Il nome del file non può contenere `:` come carattere su alcuni sistemi operativi, quindi si potrebbe usare una versione breve senza delimitatori, ma alcuni parser potrebbero fallire.

Un buon compromesso tra compatibilità e risoluzione temporale è non specificare minuti, secondi, ecc. Non credo tra l'altro sarebbe particolarmente utile in questo caso. Di conseguenza possiamo utilizzare `%Y-%m-%dT%HZ`.

**Comment by frafra** [comment]
Un approccio generico che non richiede di modificare gli script che si occupano della generazione degli estratti, può essere leggere la data di modifica dei vari file. Questa data potrebbe essere leggermente più recente di quella ai quali effettivamente gli estratti si riferiscono, ma ipotizzo che questa differenza sia negligibile.

Ho aggiunto il supporto agli script Lua a nginx, installando `libnginx-mod-http-lua` e ho impostato il nome del file tramite l'header HTTP `Content-Disposition` in base alla data di creazione, calcolata ogni volta al volo tramite un blocco di codice Lua che accede al file via `stat`.

```nginx
lua_code_cache off;
if ( $request_filename ~ "^(.*)/(.+)\.(gpkg|osm.pbf|obf)$" ) {
	set $bname $2;
	set $ext $3;
	set_by_lua_block $timestamp {
		local file = assert(io.popen("stat -c %Y " .. ngx.var.request_filename))
		file:flush()
		local last_modified = file:read()
		file:close()
		local last_modified_human = os.date("%Y-%m-%dT%HZ", last_modified)
		return last_modified_human;
	}
	add_header Content-Disposition 'attachment; filename="$bname-$timestamp.$ext"';
}
```
